### ISSUE TITLE
Error/Success handling for x-ajax

### ISSUE THREAD

**Issue by josh-tt** [ekwoka/alpine-plugins#1]
Would be great if x-ajax provided users with response codes for handling errors, doing loading animations etc.

**Comment by ekwoka** [comment]
🤔  I'd imagine the best way would be with `@load` and `@error` handlers right? to mimic the more native behavior of object loading elements.

**Comment by josh-tt** [comment]
Not sure. I just use an alpine store for now which works ok for the loading animations at least. Errors not much of a concern as I'm fetching my own content

**Comment by ekwoka** [comment]
There could be a way to also key into the `x-transition` stuff 🤔 

I'm doing some deep dives in Alpine right now, so I'll poke around

**Comment by josh-tt** [comment]
That would be handy. Good luck

**Comment by ekwoka** [comment]
Resolved in 0.3.0
