### ISSUE TITLE
I'm sure it works, I just don't know what I'm doing wrong...

### ISSUE THREAD

**Issue by simonferndriger** [ekwoka/alpine-plugins#19]
When I'm using `<div x-ajax="http://localhost:5173/_new/search.html" @load="console.warn('ok')" @error="console.warn($event.detail)"></div>` I get the error message:

> Alpine Expression Error: Unexpected token ':' Expression: "http://localhost:5173/_new/search.html"

When I'm using `<div x-ajax="/_new/search.html" @load="console.warn('ok')" @error="console.warn($event.detail)"></div>` I'm getting the error message:

> app.js:2456 Alpine Expression Error: Invalid regular expression flags. Expression: "/_new/search.html"

What am I doing wrong here?

**Comment by ekwoka** [comment]
It needs to not be the url directly, but a JS expression that resolves to a string.

So in these cases you can just put `'` around the paths.

**Comment by simonferndriger** [comment]
Got it, thanks!

Merry Xmas 🎄

**Comment by simonferndriger** [comment]
I assume there is no current workaround to make `<template x-teleport="#headerdialogs" x-ajax="...">` work?
